/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 *
 * This file is part of IOWarp Core.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef CHIMAERA_INCLUDE_CHIMAERA_GPU_CONTAINER_H_
#define CHIMAERA_INCLUDE_CHIMAERA_GPU_CONTAINER_H_

// gpu_coroutine.h MUST be included first — it blocks libstdc++ <coroutine>
// and provides GPU-compatible std::coroutine_handle for Clang CUDA.
#include "chimaera/gpu_coroutine.h"
#include "chimaera/types.h"
#include "chimaera/pool_query.h"
#include "chimaera/task.h"
#include "chimaera/local_task_archives.h"

namespace chi {
namespace gpu {

/**
 * Result of LocalAllocTask: task + co-allocated RunContext
 */
struct TaskContextBlock {
  hipc::FullPtr<Task> task_ptr;
  RunContext *rctx;
};

/**
 * GPU-side container base class.
 *
 * Uses an inline function pointer table instead of virtual dispatch.
 * This eliminates one global memory dereference per call (no vtable chase).
 * Function pointers are set by the derived class constructor (autogenerated).
 *
 * Run() returns chi::gpu::TaskResume (a C++20 coroutine type) to support
 * yielding and cooperative multitasking on the GPU.
 */
class Container {
 public:
  // ====================================================================
  // Function pointer types
  // ====================================================================
  using RunFn = TaskResume (*)(Container *, u32, hipc::FullPtr<Task>, RunContext &);
  using AllocTaskFn = TaskContextBlock (*)(Container *, u32, size_t);
  using WrapLoadTaskFn = void (*)(Container *, u32, WrapLoadArchive &, const hipc::FullPtr<Task> &);
  using WrapSaveTaskFn = void (*)(Container *, u32, WrapSaveArchive &, const hipc::FullPtr<Task> &);
  using DefaultLoadTaskFn = void (*)(Container *, u32, DefaultLoadArchive &, const hipc::FullPtr<Task> &);
  using DefaultSaveTaskFn = void (*)(Container *, u32, DefaultSaveArchive &, const hipc::FullPtr<Task> &);
  using AllocLoadTaskDefaultFn = hipc::FullPtr<Task> (*)(Container *, u32, DefaultLoadArchive &);
  using AllocLoadTaskWrapFn = hipc::FullPtr<Task> (*)(Container *, u32, WrapLoadArchive &);
  using LoadTaskOutputFn = void (*)(Container *, u32, DefaultLoadArchive &, const hipc::FullPtr<Task> &);
  using DestroyTaskFn = void (*)(Container *, u32, hipc::FullPtr<Task> &);

  // ====================================================================
  // Data members
  // ====================================================================
  PoolId pool_id_;
  u32 container_id_;

  // Inline function pointer table (one global memory read per dispatch)
  RunFn run_;
  AllocTaskFn alloc_task_;
  AllocLoadTaskDefaultFn alloc_load_task_default_;
  AllocLoadTaskWrapFn alloc_load_task_wrap_;
  WrapLoadTaskFn load_task_wrap_;
  DefaultLoadTaskFn load_task_default_;
  WrapSaveTaskFn save_task_wrap_;
  DefaultSaveTaskFn save_task_default_;
  LoadTaskOutputFn load_task_output_;
  DestroyTaskFn destroy_task_;

  // ====================================================================
  // Constructor
  // ====================================================================
  HSHM_GPU_FUN Container()
      : container_id_(0),
        run_(nullptr), alloc_task_(nullptr),
        alloc_load_task_default_(nullptr), alloc_load_task_wrap_(nullptr),
        load_task_wrap_(nullptr), load_task_default_(nullptr),
        save_task_wrap_(nullptr), save_task_default_(nullptr),
        load_task_output_(nullptr), destroy_task_(nullptr) {}
  ~Container() = default;

  /**
   * Initialize the GPU container
   * @param pool_id Pool identifier
   * @param container_id Container ID (typically node_id)
   */
  HSHM_GPU_FUN void Init(const PoolId &pool_id, u32 container_id) {
    pool_id_ = pool_id;
    container_id_ = container_id;
  }

  // ====================================================================
  // Dispatch methods (call through function pointers, single deref)
  // ====================================================================

  HSHM_GPU_FUN TaskResume Run(u32 method, hipc::FullPtr<Task> task_ptr,
                               RunContext &rctx) {
    return run_(this, method, task_ptr, rctx);
  }

  HSHM_GPU_FUN TaskContextBlock LocalAllocTask(u32 method, size_t stack_size = 0) {
    return alloc_task_(this, method, stack_size);
  }

  HSHM_GPU_FUN hipc::FullPtr<Task> LocalAllocLoadTask(u32 method, DefaultLoadArchive &archive) {
    return alloc_load_task_default_(this, method, archive);
  }

  HSHM_GPU_FUN hipc::FullPtr<Task> LocalAllocLoadTask(u32 method, WrapLoadArchive &archive) {
    return alloc_load_task_wrap_(this, method, archive);
  }

  HSHM_GPU_FUN void LocalLoadTask(u32 method, DefaultLoadArchive &archive,
                                    const hipc::FullPtr<Task> &task) {
    load_task_default_(this, method, archive, task);
  }

  HSHM_GPU_FUN void LocalLoadTask(u32 method, WrapLoadArchive &archive,
                                    const hipc::FullPtr<Task> &task) {
    load_task_wrap_(this, method, archive, task);
  }

  HSHM_GPU_FUN void LocalSaveTask(u32 method, DefaultSaveArchive &archive,
                                    const hipc::FullPtr<Task> &task) {
    save_task_default_(this, method, archive, task);
  }

  HSHM_GPU_FUN void LocalSaveTask(u32 method, WrapSaveArchive &archive,
                                    const hipc::FullPtr<Task> &task) {
    save_task_wrap_(this, method, archive, task);
  }

  HSHM_GPU_FUN void LocalLoadTaskOutput(u32 method, DefaultLoadArchive &archive,
                                          const hipc::FullPtr<Task> &task) {
    load_task_output_(this, method, archive, task);
  }

  HSHM_GPU_FUN void LocalDestroyTask(u32 method, hipc::FullPtr<Task> &task) {
    destroy_task_(this, method, task);
  }

  /**
   * Get remaining work for load balancing
   * @return Amount of work remaining (0 = idle)
   */
  HSHM_GPU_FUN u64 GetWorkRemaining() const { return 0; }
};

}  // namespace gpu
}  // namespace chi

#endif  // CHIMAERA_INCLUDE_CHIMAERA_GPU_CONTAINER_H_
