// Auto-generated GPU work orchestrator module registry
// This file is autogenerated - do not edit manually.

#ifndef CHIMAERA_AUTOGEN_GPU_WORK_ORCHESTRATOR_MODULES_H_
#define CHIMAERA_AUTOGEN_GPU_WORK_ORCHESTRATOR_MODULES_H_

#include "chimaera/MOD_NAME/MOD_NAME_gpu_runtime.h"
#include "chimaera/admin/admin_gpu_runtime.h"
#include "chimaera/bdev/bdev_gpu_runtime.h"
#include "wrp_cte/core/core_gpu_runtime.h"

#include "chimaera/gpu_container.h"
#include "chimaera/types.h"
#include <cstring>

namespace chi {
namespace gpu {

/**
 * Kernel to allocate a GPU container by module index.
 * Runs in the orchestrator's CUDA module context so vtables are correct.
 */
__global__ void _gpu_alloc_container(Container **out, u32 module_id,
                                      const PoolId *pid, u32 cid) {
  Container *obj = nullptr;
  switch (module_id) {
    case 0: obj = new chimaera::MOD_NAME::GpuRuntime(); break;
    case 1: obj = new chimaera::admin::GpuRuntime(); break;
    case 2: obj = new chimaera::bdev::GpuRuntime(); break;
    case 3: obj = new wrp_cte::core::GpuRuntime(); break;
    default: break;
  }
  if (obj) obj->Init(*pid, cid);
  *out = obj;
}

/**
 * Map ChiMod name to module ID for GPU container allocation.
 */
inline u32 GetGpuModuleId(const char *chimod_name) {
  if (strcmp(chimod_name, "chimaera_MOD_NAME") == 0) return 0;
  if (strcmp(chimod_name, "chimaera_admin") == 0) return 1;
  if (strcmp(chimod_name, "chimaera_bdev") == 0) return 2;
  if (strcmp(chimod_name, "wrp_cte_core") == 0) return 3;
  return 0xFFFFFFFF;
}

/**
 * Host function to allocate a GPU container.
 * @return Device pointer to allocated container, or nullptr
 */
inline void *AllocGpuContainerHost(const PoolId &pool_id, u32 container_id,
                                    const char *chimod_name) {
  u32 module_id = GetGpuModuleId(chimod_name);
  if (module_id == 0xFFFFFFFF) return nullptr;

  void *stream = hshm::GpuApi::CreateStream();
  Container **d_out = hshm::GpuApi::Malloc<Container *>(sizeof(Container *));
  PoolId *d_pid = hshm::GpuApi::Malloc<PoolId>(sizeof(PoolId));
  hshm::GpuApi::Memcpy(d_pid, &pool_id, sizeof(PoolId));
  _gpu_alloc_container<<<1, 1, 0,
      static_cast<cudaStream_t>(stream)>>>(d_out, module_id, d_pid, container_id);
  hshm::GpuApi::Synchronize(stream);
  Container *h_ptr = nullptr;
  hshm::GpuApi::Memcpy(&h_ptr, d_out, sizeof(Container *));
  hshm::GpuApi::Free(d_out);
  hshm::GpuApi::Free(d_pid);
  hshm::GpuApi::DestroyStream(stream);
  return static_cast<void *>(h_ptr);
}

}  // namespace gpu
}  // namespace chi

#endif  // CHIMAERA_AUTOGEN_GPU_WORK_ORCHESTRATOR_MODULES_H_
