# IOWarp Core - Conda Recipe (rattler-build format)
#
# This recipe supports two modes:
#   1. Preset mode: Uses CMakePresets.json directly for reproducible binary builds
#   2. Custom mode: Allows individual cmake flag overrides for source builds
#
# Usage:
#   rattler-build build --recipe installers/conda/ --variant-config installers/conda/variants/release.yaml
#   rattler-build build --recipe installers/conda/ --variant-config installers/conda/variants/cuda.yaml
#   rattler-build build --recipe installers/conda/ --variant-config installers/conda/variants/custom.yaml

context:
  version: "1.0.0"

package:
  name: iowarp-core
  version: ${{ version }}

source:
  path: ../..

build:
  number: 0
  string: ${{ preset }}_h${{ hash }}
  script:
    env:
      CMAKE_GENERATOR: Ninja
      # Suppress GCC false positive warnings from aggressive inlining (GCC bugs #99578, #100611)
      CXXFLAGS: "-Wno-array-bounds -Wno-maybe-uninitialized -Wno-stringop-overflow"
      # Force CMake to use only conda packages, not system libraries
      CMAKE_PREFIX_PATH: ${{ PREFIX }}
      PKG_CONFIG_PATH: ${{ PREFIX }}/lib/pkgconfig:${{ PREFIX }}/share/pkgconfig
      # Prevent finding system libraries
      CMAKE_FIND_ROOT_PATH: ${{ PREFIX }}
      CMAKE_FIND_ROOT_PATH_MODE_LIBRARY: ONLY
      CMAKE_FIND_ROOT_PATH_MODE_INCLUDE: ONLY
      CMAKE_FIND_ROOT_PATH_MODE_PACKAGE: ONLY
    content:
      - cmake --preset=${{ preset }} -DCMAKE_INSTALL_PREFIX=${{ PREFIX }} -DCMAKE_PREFIX_PATH=${{ PREFIX }} -DCMAKE_FIND_ROOT_PATH=${{ PREFIX }} -DWRP_CORE_ENABLE_CONDA=ON
      - cmake --build build --parallel
      - cmake --install build

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake >=3.20
    - ninja
    - pkg-config
  host:
    - python
    - zeromq
    - yaml-cpp
    - cereal
    - hdf5
    - catch2
    - libaio
    - liburing
  run:
    - python
    - zeromq
    - yaml-cpp
    - cereal
    - hdf5
    - catch2
    - libaio
    - liburing

tests:
  - script:
      # Just verify the library files exist (chimaera runtime start is a daemon)
      - test -f $PREFIX/lib/libchimaera_cxx.so || test -f $PREFIX/lib/libchimaera_cxx.dylib

about:
  homepage: https://www.iowarp.ai
  license: BSD-3-Clause
  license_file: LICENSE
  summary: IOWarp Context Management Platform - AI-accelerated scientific workflow orchestration
  description: |
    IOWarp Core provides a unified framework for context-aware data management
    in scientific workflows, including the Context Transfer Engine (CTE),
    Context Assimilation Engine (CAE), and Context Exploration Engine (CEE).
  repository: https://github.com/iowarp/iowarp-core
  documentation: https://docs.iowarp.ai

extra:
  recipe-maintainers:
    - lukemartinlogan
