// Auto-generated GPU lib_exec for bdev
// Include inside GpuRuntime class body
// This file is autogenerated - do not edit manually.

template <typename ArchiveT>
HSHM_GPU_FUN void LoadTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  switch (method) {
    case Method::kAllocateBlocks: {
      auto typed = task.template Cast<AllocateBlocksTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kFreeBlocks: {
      auto typed = task.template Cast<FreeBlocksTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kWrite: {
      auto typed = task.template Cast<WriteTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kRead: {
      auto typed = task.template Cast<ReadTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kUpdate: {
      auto typed = task.template Cast<UpdateTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    default: break;
  }
}

template <typename ArchiveT>
HSHM_GPU_FUN void SaveTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  switch (method) {
    case Method::kAllocateBlocks:
      task.template Cast<AllocateBlocksTask>()->SerializeOut(archive);
      break;
    case Method::kFreeBlocks:
      task.template Cast<FreeBlocksTask>()->SerializeOut(archive);
      break;
    case Method::kWrite:
      task.template Cast<WriteTask>()->SerializeOut(archive);
      break;
    case Method::kRead:
      task.template Cast<ReadTask>()->SerializeOut(archive);
      break;
    case Method::kUpdate:
      task.template Cast<UpdateTask>()->SerializeOut(archive);
      break;
    default: break;
  }
}

static HSHM_GPU_FUN chi::gpu::TaskResume RunImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> task_ptr, chi::gpu::RunContext &rctx) {
  auto *self = static_cast<GpuRuntime *>(self_);
  switch (method) {
    case Method::kAllocateBlocks:
      co_await self->AllocateBlocks(task_ptr.template Cast<AllocateBlocksTask>(), rctx);
      break;
    case Method::kFreeBlocks:
      co_await self->FreeBlocks(task_ptr.template Cast<FreeBlocksTask>(), rctx);
      break;
    case Method::kWrite:
      co_await self->Write(task_ptr.template Cast<WriteTask>(), rctx);
      break;
    case Method::kRead:
      co_await self->Read(task_ptr.template Cast<ReadTask>(), rctx);
      break;
    case Method::kUpdate:
      co_await self->Update(task_ptr.template Cast<UpdateTask>(), rctx);
      break;
    default: break;
  }
  co_return;
}

static HSHM_GPU_FUN chi::gpu::TaskContextBlock AllocTaskImpl(
    chi::gpu::Container *self_, chi::u32 method, size_t stack_size) {
  auto *alloc = CHI_IPC->GetPrivAlloc();
  if (!alloc) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
  size_t rctx_total = sizeof(chi::gpu::RunContext) + stack_size;
  switch (method) {
    case Method::kAllocateBlocks: {
      auto fp = alloc->template AllocateObjs<char>(sizeof(AllocateBlocksTask) + rctx_total);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      new (fp.ptr_) AllocateBlocksTask();
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(fp.ptr_ + sizeof(AllocateBlocksTask));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    case Method::kFreeBlocks: {
      auto fp = alloc->template AllocateObjs<char>(sizeof(FreeBlocksTask) + rctx_total);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      new (fp.ptr_) FreeBlocksTask();
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(fp.ptr_ + sizeof(FreeBlocksTask));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    case Method::kWrite: {
      auto fp = alloc->template AllocateObjs<char>(sizeof(WriteTask) + rctx_total);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      new (fp.ptr_) WriteTask();
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(fp.ptr_ + sizeof(WriteTask));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    case Method::kRead: {
      auto fp = alloc->template AllocateObjs<char>(sizeof(ReadTask) + rctx_total);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      new (fp.ptr_) ReadTask();
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(fp.ptr_ + sizeof(ReadTask));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    case Method::kUpdate: {
      auto fp = alloc->template AllocateObjs<char>(sizeof(UpdateTask) + rctx_total);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      new (fp.ptr_) UpdateTask();
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(fp.ptr_ + sizeof(UpdateTask));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    default: return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
  }
}

static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method, chi::DefaultLoadArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto block = self->alloc_task_(self_, method, 0);
  if (block.task_ptr.IsNull()) return block.task_ptr;
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  self->LoadTaskTmpl(method, ar, block.task_ptr);
  return block.task_ptr;
}

static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadTaskWrapImpl(
    chi::gpu::Container *self_, chi::u32 method, chi::WrapLoadArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto block = self->alloc_task_(self_, method, 0);
  if (block.task_ptr.IsNull()) return block.task_ptr;
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  self->LoadTaskTmpl(method, ar, block.task_ptr);
  return block.task_ptr;
}

static HSHM_GPU_FUN void LoadTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::DefaultLoadArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void LoadTaskWrapImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::WrapLoadArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void SaveTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::DefaultSaveArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  static_cast<GpuRuntime *>(self_)->SaveTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void SaveTaskWrapImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::WrapSaveArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  static_cast<GpuRuntime *>(self_)->SaveTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN chi::gpu::TaskContextBlock AllocLoadDeserImpl(
    chi::gpu::Container *self_, chi::u32 method,
    size_t stack_size, chi::WrapLoadArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto block = AllocTaskImpl(self_, method, stack_size);
  if (!block.task_ptr.IsNull()) {
    ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
    self->LoadTaskTmpl(method, ar, block.task_ptr);
  }
  return block;
}

static HSHM_GPU_FUN void LoadTaskOutputImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::DefaultLoadArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  ar.SetMsgType(chi::LocalMsgType::kSerializeOut);
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void DestroyTaskImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> &task) {
  if (task.IsNull()) return;
  switch (method) {
    case Method::kAllocateBlocks:
      task.template Cast<AllocateBlocksTask>().ptr_->~AllocateBlocksTask();
      break;
    case Method::kFreeBlocks:
      task.template Cast<FreeBlocksTask>().ptr_->~FreeBlocksTask();
      break;
    case Method::kWrite:
      task.template Cast<WriteTask>().ptr_->~WriteTask();
      break;
    case Method::kRead:
      task.template Cast<ReadTask>().ptr_->~ReadTask();
      break;
    case Method::kUpdate:
      task.template Cast<UpdateTask>().ptr_->~UpdateTask();
      break;
    default: task.ptr_->~Task(); break;
  }
}

HSHM_GPU_FUN GpuRuntime() {
  run_ = &RunImpl;
  alloc_task_ = &AllocTaskImpl;
  alloc_load_deser_ = &AllocLoadDeserImpl;
  alloc_load_task_default_ = &AllocLoadTaskDefaultImpl;
  alloc_load_task_wrap_ = &AllocLoadTaskWrapImpl;
  load_task_default_ = &LoadTaskDefaultImpl;
  load_task_wrap_ = &LoadTaskWrapImpl;
  save_task_default_ = &SaveTaskDefaultImpl;
  save_task_wrap_ = &SaveTaskWrapImpl;
  load_task_output_ = &LoadTaskOutputImpl;
  destroy_task_ = &DestroyTaskImpl;
}
