// Auto-generated GPU lib_exec for bdev
// Include inside GpuRuntime class body
// This file is autogenerated - do not edit manually.

HSHM_GPU_FUN chi::gpu::TaskResume Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr,
                       chi::gpu::RunContext &rctx) override {
  switch (method) {
    case Method::kUpdate: {
      auto typed = task_ptr.template Cast<UpdateTask>();
      co_await Update(typed, rctx);
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed = task_ptr.template Cast<AllocateBlocksTask>();
      co_await AllocateBlocks(typed, rctx);
      break;
    }
    case Method::kFreeBlocks: {
      auto typed = task_ptr.template Cast<FreeBlocksTask>();
      co_await FreeBlocks(typed, rctx);
      break;
    }
    case Method::kWrite: {
      auto typed = task_ptr.template Cast<WriteTask>();
      co_await Write(typed, rctx);
      break;
    }
    case Method::kRead: {
      auto typed = task_ptr.template Cast<ReadTask>();
      co_await Read(typed, rctx);
      break;
    }
    default: break;
  }
  co_return;
}

HSHM_GPU_FUN hipc::FullPtr<chi::Task> LocalAllocLoadTask(
    chi::u32 method, chi::LocalLoadTaskArchive &archive) override {
  auto *alloc = gpu_alloc_;
  switch (method) {
    case Method::kUpdate: {
      auto task = alloc->template AllocateObjs<UpdateTask>(1);
      if (task.IsNull()) return hipc::FullPtr<chi::Task>::GetNull();
      new (task.ptr_) UpdateTask();
      archive.SetMsgType(chi::LocalMsgType::kSerializeIn);
      task.ptr_->SerializeIn(archive);
      return task.template Cast<chi::Task>();
    }
    case Method::kAllocateBlocks: {
      auto task = alloc->template AllocateObjs<AllocateBlocksTask>(1);
      if (task.IsNull()) return hipc::FullPtr<chi::Task>::GetNull();
      new (task.ptr_) AllocateBlocksTask();
      archive.SetMsgType(chi::LocalMsgType::kSerializeIn);
      task.ptr_->SerializeIn(archive);
      return task.template Cast<chi::Task>();
    }
    case Method::kFreeBlocks: {
      auto task = alloc->template AllocateObjs<FreeBlocksTask>(1);
      if (task.IsNull()) return hipc::FullPtr<chi::Task>::GetNull();
      new (task.ptr_) FreeBlocksTask();
      archive.SetMsgType(chi::LocalMsgType::kSerializeIn);
      task.ptr_->SerializeIn(archive);
      return task.template Cast<chi::Task>();
    }
    case Method::kWrite: {
      auto task = alloc->template AllocateObjs<WriteTask>(1);
      if (task.IsNull()) return hipc::FullPtr<chi::Task>::GetNull();
      new (task.ptr_) WriteTask();
      archive.SetMsgType(chi::LocalMsgType::kSerializeIn);
      task.ptr_->SerializeIn(archive);
      return task.template Cast<chi::Task>();
    }
    case Method::kRead: {
      auto task = alloc->template AllocateObjs<ReadTask>(1);
      if (task.IsNull()) return hipc::FullPtr<chi::Task>::GetNull();
      new (task.ptr_) ReadTask();
      archive.SetMsgType(chi::LocalMsgType::kSerializeIn);
      task.ptr_->SerializeIn(archive);
      return task.template Cast<chi::Task>();
    }
    default: return hipc::FullPtr<chi::Task>::GetNull();
  }
}

HSHM_GPU_FUN void LocalSaveTask(
    chi::u32 method, chi::LocalSaveTaskArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override {
  switch (method) {
    case Method::kUpdate: {
      auto typed = task.template Cast<UpdateTask>();
      typed->SerializeOut(archive);
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed = task.template Cast<AllocateBlocksTask>();
      typed->SerializeOut(archive);
      break;
    }
    case Method::kFreeBlocks: {
      auto typed = task.template Cast<FreeBlocksTask>();
      typed->SerializeOut(archive);
      break;
    }
    case Method::kWrite: {
      auto typed = task.template Cast<WriteTask>();
      typed->SerializeOut(archive);
      break;
    }
    case Method::kRead: {
      auto typed = task.template Cast<ReadTask>();
      typed->SerializeOut(archive);
      break;
    }
    default: break;
  }
}

HSHM_GPU_FUN void LocalLoadTaskOutput(
    chi::u32 method, chi::LocalLoadTaskArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override {
  archive.SetMsgType(chi::LocalMsgType::kSerializeOut);
  switch (method) {
    case Method::kUpdate: {
      auto typed = task.template Cast<UpdateTask>();
      typed->SerializeOut(archive);
      break;
    }
    case Method::kAllocateBlocks: {
      auto typed = task.template Cast<AllocateBlocksTask>();
      typed->SerializeOut(archive);
      break;
    }
    case Method::kFreeBlocks: {
      auto typed = task.template Cast<FreeBlocksTask>();
      typed->SerializeOut(archive);
      break;
    }
    case Method::kWrite: {
      auto typed = task.template Cast<WriteTask>();
      typed->SerializeOut(archive);
      break;
    }
    case Method::kRead: {
      auto typed = task.template Cast<ReadTask>();
      typed->SerializeOut(archive);
      break;
    }
    default: break;
  }
}

HSHM_GPU_FUN void LocalDestroyTask(
    chi::u32 method, hipc::FullPtr<chi::Task> &task) override {
  if (task.IsNull()) return;
  switch (method) {
    case Method::kUpdate:
      task.template Cast<UpdateTask>().ptr_->~UpdateTask();
      break;
    case Method::kAllocateBlocks:
      task.template Cast<AllocateBlocksTask>().ptr_->~AllocateBlocksTask();
      break;
    case Method::kFreeBlocks:
      task.template Cast<FreeBlocksTask>().ptr_->~FreeBlocksTask();
      break;
    case Method::kWrite:
      task.template Cast<WriteTask>().ptr_->~WriteTask();
      break;
    case Method::kRead:
      task.template Cast<ReadTask>().ptr_->~ReadTask();
      break;
    default:
      task.ptr_->~Task();
      break;
  }
}
