/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 *
 * This file is part of IOWarp Core.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * GPU Work Orchestrator implementation
 *
 * A persistent GPU kernel that polls CPU->GPU and GPU->GPU queues for tasks,
 * dispatches them to GPU-side containers via gpu::Worker / gpu::PoolManager,
 * and communicates results back through FutureShm completion flags.
 *
 * Execution model: warp-level dispatch. Each warp gets one Worker instance.
 * Lane 0 of each warp acts as the scheduler (queue polling, deserialization,
 * serialization), while all 32 threads synchronize via __syncwarp().
 *
 * All GPU containers are allocated within this CUDA module's context, so
 * virtual function dispatch (vtables) works correctly. No companion .so
 * files or function pointer fixups are needed.
 */

#if HSHM_ENABLE_CUDA || HSHM_ENABLE_ROCM

// Must be included first — blocks libstdc++ <coroutine> and provides
// GPU-compatible std::coroutine_handle for Clang CUDA compilation.
#include "chimaera/gpu_coroutine_handle.h"

#include "chimaera/ipc_manager.h"
#include "chimaera/gpu_work_orchestrator.h"
#include "chimaera/gpu_container.h"
#include "chimaera/gpu_pool_manager.h"
#include "chimaera/gpu_worker.h"
#include "chimaera/config_manager.h"

// Include autogenerated GPU module registry (container headers + alloc kernel)
#include "autogen/gpu_work_orchestrator_modules.h"

namespace chi {

/**
 * GPU Work Orchestrator - persistent kernel for GPU task execution.
 * Uses warp-level dispatch: one Worker per warp, lane 0 schedules.
 */
__global__ void chimaera_gpu_orchestrator(gpu::PoolManager *pool_mgr,
                                           gpu::WorkOrchestratorControl *control,
                                           IpcManagerGpuInfo gpu_info,
                                           u32 num_blocks) {
  // All threads: initialize per-block IpcManager (ArenaAllocators).
  // num_blocks is used to partition the backend memory among blocks.
  CHIMAERA_GPU_ORCHESTRATOR_INIT(gpu_info, num_blocks);

  u32 warp_id = IpcManager::GetWarpId();
  u32 lane_id = IpcManager::GetLaneId();

  // Shared pointer-per-warp: lane 0 sets its warp's pointer to a heap-allocated
  // GpuRunContext[32] array. All lanes read it after __syncwarp().
  constexpr u32 kMaxWarpsPerBlock = 32;  // 1024 threads / 32
  __shared__ gpu::GpuRunContext *s_active_ptrs[kMaxWarpsPerBlock];
  u32 warp_in_block = threadIdx.x / 32;
  if (threadIdx.x == 0) {
    memset(s_active_ptrs, 0, sizeof(s_active_ptrs));
  }
  __syncthreads();

  // Thread 0 of block 0 signals that the orchestrator is running
  if (blockIdx.x == 0 && threadIdx.x == 0) {
    control->running_flag = 1;
    __threadfence_system();  // Flush to CPU-visible memory
  }

  // Each warp polls its own lane from the gpu2gpu queue
  gpu::Worker worker;
  worker.Init(warp_id,
              warp_id,
              gpu_info.cpu2gpu_queue,
              gpu_info.gpu2gpu_queue,
              gpu_info.internal_queue,
              pool_mgr,
              gpu_info.cpu2gpu_queue_base,
              control,
              &s_active_ptrs[warp_in_block]);

  // Poll until exit signal
  while (!control->exit_flag) {
    worker.PollOnce(lane_id);
  }

  worker.Finalize();
}

//==============================================================================
// gpu::WorkOrchestrator out-of-class method implementations
//==============================================================================

/**
 * Launch the persistent GPU work orchestrator.
 */
bool gpu::WorkOrchestrator::Launch(const IpcManagerGpuInfo &gpu_info, u32 blocks,
                                    u32 threads_per_block) {
  if (is_launched_) {
    return true;
  }

  // Allocate WorkOrchestratorControl in pinned host memory
  gpu::WorkOrchestratorControl *pinned_control = nullptr;
  cudaMallocHost(&pinned_control, sizeof(gpu::WorkOrchestratorControl));
  control_ = pinned_control;
  if (!control_) {
    HLOG(kError, "gpu::WorkOrchestrator: Failed to allocate control structure");
    return false;
  }
  memset(control_, 0, sizeof(gpu::WorkOrchestratorControl));

  // Allocate gpu::PoolManager on device
  gpu::PoolManager *d_pm = hshm::GpuApi::Malloc<gpu::PoolManager>(
      sizeof(gpu::PoolManager));
  if (!d_pm) {
    HLOG(kError, "gpu::WorkOrchestrator: Failed to allocate GPU PoolManager");
    cudaFreeHost(control_);
    control_ = nullptr;
    return false;
  }
  d_pool_mgr_ = d_pm;

  // Initialize PoolManager on device (zero-initialize)
  gpu::PoolManager host_pm;
  hshm::GpuApi::Memcpy(d_pm, &host_pm, sizeof(gpu::PoolManager));

  // Set GPU stack size. 32KB per thread for deep dispatch + serialization.
  cudaDeviceSetLimit(cudaLimitStackSize, 32768);
  cudaDeviceSetLimit(cudaLimitPrintfFifoSize, 8 * 1024 * 1024);

  // Create dedicated stream
  stream_ = hshm::GpuApi::CreateStream();

  // Save launch parameters for Pause/Resume
  blocks_ = blocks;
  threads_per_block_ = threads_per_block;

  // Update lane counts to match actual warp count
  IpcManagerGpuInfo launch_info = gpu_info;
  u32 num_warps = (blocks * threads_per_block) / 32;
  if (num_warps == 0) num_warps = 1;
  launch_info.gpu2gpu_num_lanes = num_warps;
  launch_info.internal_num_lanes = num_warps;

  // Launch persistent GPU work orchestrator.
  HLOG(kInfo, "Launching GPU work orchestrator with {} blocks, {} threads/block ({} warps)",
       blocks, threads_per_block, launch_info.gpu2gpu_num_lanes);
  chimaera_gpu_orchestrator<<<blocks, threads_per_block, 0,
      static_cast<cudaStream_t>(stream_)>>>(
      d_pm, control_, launch_info, blocks);

  is_launched_ = true;
  HLOG(kInfo, "GPU work orchestrator launched successfully");
  return true;
}

/** Stop the GPU work orchestrator and free resources. */
void gpu::WorkOrchestrator::Finalize() {
  if (!is_launched_) {
    return;
  }

  if (control_) {
    control_->exit_flag = 1;
  }

  if (stream_) {
    hshm::GpuApi::Synchronize(stream_);
    hshm::GpuApi::DestroyStream(stream_);
    stream_ = nullptr;
  } else {
    hshm::GpuApi::Synchronize();
  }

  if (d_pool_mgr_) {
    hshm::GpuApi::Free(d_pool_mgr_);
    d_pool_mgr_ = nullptr;
  }
  if (control_) {
    cudaFreeHost(control_);
    control_ = nullptr;
  }

  is_launched_ = false;
  HLOG(kInfo, "GPU work orchestrator finalized");
}

/** Pause the GPU work orchestrator. */
void gpu::WorkOrchestrator::Pause() {
  if (!is_launched_) {
    return;
  }
  control_->exit_flag = 1;
  HLOG(kInfo, "GPU work orchestrator: exit_flag set, waiting for kernel...");

  cudaError_t pre_err = cudaGetLastError();
  if (pre_err != cudaSuccess) {
    HLOG(kError, "GPU work orchestrator: pre-sync CUDA error: {}",
         cudaGetErrorString(pre_err));
  }

  hshm::GpuApi::Synchronize(stream_);
  HLOG(kInfo, "GPU work orchestrator: kernel synchronized");
  is_launched_ = false;
  HLOG(kInfo, "GPU work orchestrator paused");
}

/** Resume a paused GPU work orchestrator. */
void gpu::WorkOrchestrator::Resume(const IpcManagerGpuInfo &gpu_info) {
  if (is_launched_) {
    return;
  }

  cudaError_t pre_err = cudaGetLastError();
  if (pre_err != cudaSuccess) {
    HLOG(kError, "GPU work orchestrator Resume: clearing sticky CUDA error: {}",
         cudaGetErrorString(pre_err));
  }

  control_->exit_flag = 0;
  control_->running_flag = 0;

  IpcManagerGpuInfo resume_info = gpu_info;
  resume_info.skip_scratch_init = false;  // re-partition scratch for new warp count
  u32 num_warps = (blocks_ * threads_per_block_) / 32;
  if (num_warps == 0) num_warps = 1;
  resume_info.gpu2gpu_num_lanes = num_warps;
  resume_info.internal_num_lanes = num_warps;

  // Skip heap re-init — per-block allocators persist across pause/resume.
  resume_info.skip_heap_init = true;

  // Zero scratch allocator headers so non-block-0 blocks spin-wait
  // until block 0 finishes re-initialization (prevents stale ready flags).
  // Both backends are pinned host memory (GpuShmMmap), so use CPU memset.
  // The stream was fully synchronized in Pause(), so no race with GPU.
  if (resume_info.backend.data_ != nullptr) {
    memset(resume_info.backend.data_, 0, sizeof(hipc::ThreadAllocator));
  }
  if (resume_info.gpu2cpu_backend.data_ != nullptr) {
    memset(resume_info.gpu2cpu_backend.data_, 0,
           sizeof(hipc::ThreadAllocator));
  }

  auto *d_pm = static_cast<gpu::PoolManager *>(d_pool_mgr_);

  chimaera_gpu_orchestrator<<<blocks_, threads_per_block_, 0,
      static_cast<cudaStream_t>(stream_)>>>(
      d_pm, control_, resume_info, blocks_);

  cudaError_t launch_err = cudaGetLastError();
  if (launch_err != cudaSuccess) {
    HLOG(kError, "GPU work orchestrator Resume: kernel launch failed: {}",
         cudaGetErrorString(launch_err));
    is_launched_ = false;
    return;
  }

  is_launched_ = true;
  HLOG(kInfo, "GPU work orchestrator resumed with {} blocks, {} threads/block ({} warps)",
       blocks_, threads_per_block_, resume_info.gpu2gpu_num_lanes);
}

/**
 * Register a GPU container with the device-side PoolManager.
 */
void gpu::WorkOrchestrator::RegisterGpuContainer(const PoolId &pool_id,
                                                   void *gpu_container_ptr) {
  if (!d_pool_mgr_ || !gpu_container_ptr) {
    return;
  }

  auto *d_pm = static_cast<gpu::PoolManager *>(d_pool_mgr_);
  gpu::PoolManager host_pm;
  hshm::GpuApi::Memcpy(&host_pm, d_pm, sizeof(gpu::PoolManager));
  host_pm.RegisterContainer(pool_id,
                             static_cast<gpu::Container *>(gpu_container_ptr));
  hshm::GpuApi::Memcpy(d_pm, &host_pm, sizeof(gpu::PoolManager));

  HLOG(kInfo, "Registered GPU container for pool {}", pool_id);
}

/**
 * Allocate a GPU container by module name.
 * Uses the autogenerated allocation kernel which runs in this CUDA module's
 * context, ensuring vtables are correct.
 */
void *gpu::WorkOrchestrator::AllocGpuContainer(const PoolId &pool_id,
                                                 u32 container_id,
                                                 const std::string &chimod_name) {
  return gpu::AllocGpuContainerHost(pool_id, container_id, chimod_name.c_str());
}

//==============================================================================
// gpu_init_queue_kernel — device kernel for ArenaAllocator + TaskQueue init
//==============================================================================

__global__ void gpu_init_queue_kernel(char *device_data, size_t capacity,
                                       u32 num_lanes, u32 queue_depth,
                                       size_t *d_out_off) {
  if (blockIdx.x != 0 || threadIdx.x != 0) return;

  hipc::MemoryBackend proxy;
  proxy.data_ = device_data;
  proxy.data_capacity_ = capacity;

  CHI_QUEUE_ALLOC_T *alloc = proxy.MakeAlloc<CHI_QUEUE_ALLOC_T>();
  if (!alloc) { *d_out_off = static_cast<size_t>(-1); return; }

  hipc::FullPtr<TaskQueue> q = alloc->template NewObj<TaskQueue>(
      alloc, num_lanes, 2, queue_depth);
  *d_out_off = q.IsNull() ? static_cast<size_t>(-1) : q.shm_.off_.load();
}

hipc::FullPtr<TaskQueue> gpu::InitQueueOnDevice(char *device_data,
                                                  size_t capacity,
                                                  u32 num_lanes,
                                                  u32 queue_depth) {
  size_t *d_out_off = nullptr;
  cudaError_t err = cudaMalloc(&d_out_off, sizeof(size_t));
  if (err != cudaSuccess) {
    HLOG(kError, "InitQueueOnDevice: cudaMalloc for d_out_off failed: {}",
         cudaGetErrorString(err));
    return hipc::FullPtr<TaskQueue>::GetNull();
  }

  gpu_init_queue_kernel<<<1, 1>>>(device_data, capacity, num_lanes,
                                   queue_depth, d_out_off);
  err = cudaDeviceSynchronize();
  if (err != cudaSuccess) {
    HLOG(kError, "InitQueueOnDevice: kernel launch failed: {}",
         cudaGetErrorString(err));
    cudaFree(d_out_off);
    return hipc::FullPtr<TaskQueue>::GetNull();
  }

  size_t off = static_cast<size_t>(-1);
  cudaMemcpy(&off, d_out_off, sizeof(size_t), cudaMemcpyDeviceToHost);
  cudaFree(d_out_off);

  hipc::FullPtr<TaskQueue> result;
  if (off == static_cast<size_t>(-1)) {
    return hipc::FullPtr<TaskQueue>::GetNull();
  }
  result.shm_.off_ = off;
  result.shm_.alloc_id_ = hipc::AllocatorId(0, 0);
  result.ptr_ = reinterpret_cast<TaskQueue *>(device_data + off);
  return result;
}

}  // namespace chi

#endif  // HSHM_ENABLE_CUDA || HSHM_ENABLE_ROCM
