/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 *
 * This file is part of IOWarp Core.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * GPU Work Orchestrator implementation
 *
 * A persistent GPU kernel that polls CPU->GPU and GPU->GPU queues for tasks,
 * dispatches them to GPU-side containers via gpu::Worker / gpu::PoolManager,
 * and communicates results back through FutureShm completion flags.
 *
 * All GPU containers are allocated within this CUDA module's context, so
 * virtual function dispatch (vtables) works correctly. No companion .so
 * files or function pointer fixups are needed.
 */

#if HSHM_ENABLE_CUDA || HSHM_ENABLE_ROCM

// Must be included first — blocks libstdc++ <coroutine> and provides
// GPU-compatible std::coroutine_handle for Clang CUDA compilation.
#include "chimaera/gpu_coroutine_handle.h"

#include "chimaera/ipc_manager.h"
#include "chimaera/gpu_work_orchestrator.h"
#include "chimaera/gpu_container.h"
#include "chimaera/gpu_pool_manager.h"
#include "chimaera/gpu_worker.h"
#include "chimaera/config_manager.h"

// Include autogenerated GPU module registry (container headers + alloc kernel)
#include "autogen/gpu_work_orchestrator_modules.h"

namespace chi {

/**
 * GPU Work Orchestrator - persistent kernel for GPU task execution.
 */
__global__ void chimaera_gpu_orchestrator(gpu::PoolManager *pool_mgr,
                                           gpu::WorkOrchestratorControl *control,
                                           IpcManagerGpuInfo gpu_info,
                                           u32 num_blocks) {
  // All threads: initialize per-block IpcManager (ArenaAllocators).
  // num_blocks is used to partition the backend memory among blocks.
  CHIMAERA_GPU_ORCHESTRATOR_INIT(gpu_info, num_blocks);

  // Only thread 0 of each block runs the worker loop.
  // Threads 1..N-1 exit immediately after INIT so that:
  //   1. The per-block alloc_table_size remains proportional to threads_per_block
  //      (keeps the ArenaAllocator memory layout correct).
  //   2. No idle threads remain in each block's warp causing SIMT serialization
  //      overhead for thread 0's poll loop.
  // All blocks' thread 0 act as concurrent workers, each atomically popping
  // tasks from the shared queues.
  if (threadIdx.x != 0) {
    return;
  }

  control->running_flag = 1;

  gpu::Worker worker;
  worker.Init(0,
              gpu_info.cpu2gpu_queue,
              gpu_info.gpu2gpu_queue,
              pool_mgr,
              gpu_info.cpu2gpu_queue_base);

  // Poll until exit signal; yield when idle so client warps can be scheduled
  while (!control->exit_flag) {
    bool did_work = worker.PollOnce();
    if (!did_work) {
      __nanosleep(100);
    }
  }

  worker.Finalize();
}

//==============================================================================
// gpu::WorkOrchestrator out-of-class method implementations
//==============================================================================

/**
 * Launch the persistent GPU work orchestrator.
 */
bool gpu::WorkOrchestrator::Launch(const IpcManagerGpuInfo &gpu_info, u32 blocks,
                                    u32 threads_per_block) {
  if (is_launched_) {
    return true;
  }

  // Allocate WorkOrchestratorControl in pinned host memory
  gpu::WorkOrchestratorControl *pinned_control = nullptr;
  cudaMallocHost(&pinned_control, sizeof(gpu::WorkOrchestratorControl));
  control_ = pinned_control;
  if (!control_) {
    HLOG(kError, "gpu::WorkOrchestrator: Failed to allocate control structure");
    return false;
  }
  control_->exit_flag = 0;
  control_->running_flag = 0;

  // Allocate gpu::PoolManager on device
  gpu::PoolManager *d_pm = hshm::GpuApi::Malloc<gpu::PoolManager>(
      sizeof(gpu::PoolManager));
  if (!d_pm) {
    HLOG(kError, "gpu::WorkOrchestrator: Failed to allocate GPU PoolManager");
    cudaFreeHost(control_);
    control_ = nullptr;
    return false;
  }
  d_pool_mgr_ = d_pm;

  // Initialize PoolManager on device (zero-initialize)
  gpu::PoolManager host_pm;
  hshm::GpuApi::Memcpy(d_pm, &host_pm, sizeof(gpu::PoolManager));

  // Set GPU stack size. 32KB per thread for deep dispatch + serialization.
  // Only thread 0 per block runs the worker loop, so actual usage is modest.
  cudaDeviceSetLimit(cudaLimitStackSize, 32768);

  // Create dedicated stream
  stream_ = hshm::GpuApi::CreateStream();

  // Save launch parameters for Pause/Resume
  blocks_ = blocks;
  threads_per_block_ = threads_per_block;

  // Launch persistent GPU work orchestrator.
  // All threads call CHIMAERA_GPU_ORCHESTRATOR_INIT for correct memory layout,
  // then only block 0, thread 0 runs the worker loop; all others exit early.
  HLOG(kInfo, "Launching GPU work orchestrator with {} blocks, {} threads/block",
       blocks, threads_per_block);
  chimaera_gpu_orchestrator<<<blocks, threads_per_block, 0,
      static_cast<cudaStream_t>(stream_)>>>(
      d_pm, control_, gpu_info, blocks);

  is_launched_ = true;
  HLOG(kInfo, "GPU work orchestrator launched successfully");
  return true;
}

/** Stop the GPU work orchestrator and free resources. */
void gpu::WorkOrchestrator::Finalize() {
  if (!is_launched_) {
    return;
  }

  if (control_) {
    control_->exit_flag = 1;
  }

  if (stream_) {
    hshm::GpuApi::Synchronize(stream_);
    hshm::GpuApi::DestroyStream(stream_);
    stream_ = nullptr;
  } else {
    hshm::GpuApi::Synchronize();
  }

  if (d_pool_mgr_) {
    hshm::GpuApi::Free(d_pool_mgr_);
    d_pool_mgr_ = nullptr;
  }
  if (control_) {
    cudaFreeHost(control_);
    control_ = nullptr;
  }

  is_launched_ = false;
  HLOG(kInfo, "GPU work orchestrator finalized");
}

/** Pause the GPU work orchestrator. */
void gpu::WorkOrchestrator::Pause() {
  if (!is_launched_) {
    return;
  }
  control_->exit_flag = 1;
  HLOG(kInfo, "GPU work orchestrator: exit_flag set, waiting for kernel...");

  // Check for pre-existing CUDA errors before sync (sticky errors)
  cudaError_t pre_err = cudaGetLastError();
  if (pre_err != cudaSuccess) {
    HLOG(kError, "GPU work orchestrator: pre-sync CUDA error: {}",
         cudaGetErrorString(pre_err));
  }

  hshm::GpuApi::Synchronize(stream_);
  HLOG(kInfo, "GPU work orchestrator: kernel synchronized");
  is_launched_ = false;
  HLOG(kInfo, "GPU work orchestrator paused");
}

/** Resume a paused GPU work orchestrator. */
void gpu::WorkOrchestrator::Resume(const IpcManagerGpuInfo &gpu_info) {
  if (is_launched_) {
    return;
  }

  // Clear any sticky CUDA errors before launching
  cudaError_t pre_err = cudaGetLastError();
  if (pre_err != cudaSuccess) {
    HLOG(kError, "GPU work orchestrator Resume: clearing sticky CUDA error: {}",
         cudaGetErrorString(pre_err));
  }

  control_->exit_flag = 0;
  control_->running_flag = 0;

  // On resume, skip heap re-initialization to preserve existing GPU-side
  // container allocations (e.g., GpuMetadata in CTE GpuRuntime).
  IpcManagerGpuInfo resume_info = gpu_info;
  resume_info.skip_heap_init = true;

  auto *d_pm = static_cast<gpu::PoolManager *>(d_pool_mgr_);
  chimaera_gpu_orchestrator<<<blocks_, threads_per_block_, 0,
      static_cast<cudaStream_t>(stream_)>>>(
      d_pm, control_, resume_info, blocks_);

  // Check launch error
  cudaError_t launch_err = cudaGetLastError();
  if (launch_err != cudaSuccess) {
    HLOG(kError, "GPU work orchestrator Resume: kernel launch failed: {}",
         cudaGetErrorString(launch_err));
    is_launched_ = false;
    return;
  }

  is_launched_ = true;
  HLOG(kInfo, "GPU work orchestrator resumed with {} blocks, {} threads/block",
       blocks_, threads_per_block_);
}

/**
 * Register a GPU container with the device-side PoolManager.
 * Virtual dispatch is already correct since all containers are allocated
 * in this CUDA module's context.
 */
void gpu::WorkOrchestrator::RegisterGpuContainer(const PoolId &pool_id,
                                                   void *gpu_container_ptr) {
  if (!d_pool_mgr_ || !gpu_container_ptr) {
    return;
  }

  // Register container with PoolManager
  auto *d_pm = static_cast<gpu::PoolManager *>(d_pool_mgr_);
  gpu::PoolManager host_pm;
  hshm::GpuApi::Memcpy(&host_pm, d_pm, sizeof(gpu::PoolManager));
  host_pm.RegisterContainer(pool_id,
                             static_cast<gpu::Container *>(gpu_container_ptr));
  hshm::GpuApi::Memcpy(d_pm, &host_pm, sizeof(gpu::PoolManager));

  HLOG(kInfo, "Registered GPU container for pool {}", pool_id);
}

/**
 * Allocate a GPU container by module name.
 * Uses the autogenerated allocation kernel which runs in this CUDA module's
 * context, ensuring vtables are correct.
 */
void *gpu::WorkOrchestrator::AllocGpuContainer(const PoolId &pool_id,
                                                 u32 container_id,
                                                 const std::string &chimod_name) {
  return gpu::AllocGpuContainerHost(pool_id, container_id, chimod_name.c_str());
}

//==============================================================================
// gpu::InitQueueOnDevice — initialize ArenaAllocator + TaskQueue on device mem
//==============================================================================

/**
 * One-shot GPU kernel: constructs a BuddyAllocator and TaskQueue in-place
 * on device memory. Runs on a single thread (1 block, 1 thread).
 * MakeAlloc and NewObj are HSHM_CROSS_FUN so they work on GPU.
 *
 * @param device_data Base pointer of device memory (GpuMalloc data_)
 * @param capacity    Total bytes available
 * @param queue_depth Depth of the TaskQueue ring buffer
 * @param d_out_off   Device output: byte offset of the TaskQueue within data_
 */
__global__ void gpu_init_queue_kernel(char *device_data, size_t capacity,
                                       u32 queue_depth, size_t *d_out_off) {
  if (blockIdx.x != 0 || threadIdx.x != 0) return;

  // Build a minimal MemoryBackend pointing at device_data so MakeAlloc works
  hipc::MemoryBackend proxy;
  proxy.data_ = device_data;
  proxy.data_capacity_ = capacity;

  CHI_QUEUE_ALLOC_T *alloc = proxy.MakeAlloc<CHI_QUEUE_ALLOC_T>();
  if (!alloc) { *d_out_off = static_cast<size_t>(-1); return; }

  hipc::FullPtr<TaskQueue> q = alloc->template NewObj<TaskQueue>(
      alloc, 1, 2, queue_depth);
  *d_out_off = q.IsNull() ? static_cast<size_t>(-1) : q.shm_.off_.load();
}

hipc::FullPtr<TaskQueue> gpu::InitQueueOnDevice(char *device_data,
                                                  size_t capacity,
                                                  u32 queue_depth) {
  // Allocate output slot in pinned memory for the queue offset
  size_t *d_out_off = nullptr;
  cudaError_t err = cudaMalloc(&d_out_off, sizeof(size_t));
  if (err != cudaSuccess) {
    HLOG(kError, "InitQueueOnDevice: cudaMalloc for d_out_off failed: {}",
         cudaGetErrorString(err));
    return hipc::FullPtr<TaskQueue>::GetNull();
  }

  gpu_init_queue_kernel<<<1, 1>>>(device_data, capacity, queue_depth,
                                   d_out_off);
  err = cudaDeviceSynchronize();
  if (err != cudaSuccess) {
    HLOG(kError, "InitQueueOnDevice: kernel launch failed: {}",
         cudaGetErrorString(err));
    cudaFree(d_out_off);
    return hipc::FullPtr<TaskQueue>::GetNull();
  }

  size_t off = static_cast<size_t>(-1);
  cudaMemcpy(&off, d_out_off, sizeof(size_t), cudaMemcpyDeviceToHost);
  cudaFree(d_out_off);

  hipc::FullPtr<TaskQueue> result;
  if (off == static_cast<size_t>(-1)) {
    return hipc::FullPtr<TaskQueue>::GetNull();
  }
  result.shm_.off_ = off;
  result.shm_.alloc_id_ = hipc::AllocatorId(0, 0);
  result.ptr_ = reinterpret_cast<TaskQueue *>(device_data + off);
  return result;
}

}  // namespace chi

#endif  // HSHM_ENABLE_CUDA || HSHM_ENABLE_ROCM
