/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 * This file is part of IOWarp Core.
 * See COPYING file in the top-level directory.
 */

#ifndef CHIMAERA_ADMIN_GPU_RUNTIME_H_
#define CHIMAERA_ADMIN_GPU_RUNTIME_H_

#include "chimaera/gpu_container.h"

namespace chimaera::admin {

/**
 * GPU-side container for Admin ChiMod.
 * All admin methods are no-ops on GPU.
 */
class GpuRuntime : public chi::gpu::Container {
 public:
  HSHM_GPU_FUN GpuRuntime() = default;
  HSHM_GPU_FUN ~GpuRuntime() override = default;

  // Autogenerated virtual method overrides (all no-ops for admin)
  #include "autogen/admin_gpu_lib_exec.h"
};

}  // namespace chimaera::admin

#endif  // CHIMAERA_ADMIN_GPU_RUNTIME_H_
