# IOWarp Core - Conda Variant
# Optimized conda build using CMakePresets.json "conda" preset
#
# Usage: rattler-build build --recipe recipe/ --variant-config variants/conda.yaml

preset: conda
python: "3.11"

cuda_enabled: "OFF"
rocm_enabled: "OFF"
mpi_enabled: "OFF"
mpi_impl: nompi
