// Auto-generated GPU lib_exec for admin
// Include inside GpuRuntime class body
// This file is autogenerated - do not edit manually.

HSHM_GPU_FUN chi::gpu::TaskResume Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr,
                       chi::gpu::RunContext &rctx) override {
  (void)method; (void)task_ptr; (void)rctx;
  co_return;
}

HSHM_GPU_FUN hipc::FullPtr<chi::Task> LocalAllocLoadTask(
    chi::u32 method, chi::DefaultLoadArchive &archive) override {
  (void)method; (void)archive;
  return hipc::FullPtr<chi::Task>::GetNull();
}

HSHM_GPU_FUN void LocalSaveTask(
    chi::u32 method, chi::DefaultSaveArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override {
  (void)method; (void)archive; (void)task;
}
