/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 * This file is part of IOWarp Core.
 * See COPYING file in the top-level directory.
 */

#ifndef CHIMAERA_BDEV_GPU_RUNTIME_H_
#define CHIMAERA_BDEV_GPU_RUNTIME_H_

#include "chimaera/gpu_container.h"
#include "chimaera/bdev/bdev_tasks.h"
#include "chimaera/bdev/autogen/bdev_methods.h"

namespace chimaera::bdev {

/**
 * GPU-side container for the bdev module.
 *
 * Handles kUpdate, kAllocateBlocks, kFreeBlocks, kWrite, and kRead
 * directly on the GPU using device or pinned memory.
 *
 * Initialized by an UpdateTask submitted from the CPU bdev runtime's
 * Create() handler after allocating kHbm or kPinned memory.
 */
class GpuRuntime : public chi::gpu::Container {
 public:
  /// Raw u64 device pointer to the HBM (cudaMalloc) buffer (0 if unused)
  chi::u64 hbm_ptr_;
  /// Raw u64 pointer to the pinned host buffer (0 if unused)
  chi::u64 pinned_ptr_;
  /// Byte size of the HBM buffer
  chi::u64 hbm_size_;
  /// Byte size of the pinned buffer
  chi::u64 pinned_size_;
  /// Allocatable region size (= hbm_size_ for kHbm, pinned_size_ for kPinned)
  chi::u64 total_size_;
  /// BdevType enum value (chi::u32 for GPU compatibility)
  chi::u32 bdev_type_;
  /// Allocation alignment in bytes
  chi::u32 alignment_;
  /// Atomic bump-allocator cursor (advanced via atomicAdd)
  chi::u64 gpu_heap_;

  HSHM_GPU_FUN GpuRuntime()
      : hbm_ptr_(0), pinned_ptr_(0),
        hbm_size_(0), pinned_size_(0), total_size_(0),
        bdev_type_(0), alignment_(4096), gpu_heap_(0) {}

  HSHM_GPU_FUN ~GpuRuntime() override = default;

  HSHM_GPU_FUN chi::gpu::TaskResume Update(hipc::FullPtr<UpdateTask> task,
                            chi::gpu::RunContext &rctx);

  HSHM_GPU_FUN chi::gpu::TaskResume AllocateBlocks(hipc::FullPtr<AllocateBlocksTask> task,
                                    chi::gpu::RunContext &rctx);

  HSHM_GPU_FUN chi::gpu::TaskResume FreeBlocks(hipc::FullPtr<FreeBlocksTask> task,
                                chi::gpu::RunContext &rctx);

  HSHM_GPU_FUN chi::gpu::TaskResume Write(hipc::FullPtr<WriteTask> task,
                           chi::gpu::RunContext &rctx);

  HSHM_GPU_FUN chi::gpu::TaskResume Read(hipc::FullPtr<ReadTask> task,
                          chi::gpu::RunContext &rctx);

  // Autogenerated virtual method overrides (switch-case dispatch)
  #include "autogen/bdev_gpu_lib_exec.h"
};

}  // namespace chimaera::bdev

#endif  // CHIMAERA_BDEV_GPU_RUNTIME_H_
