/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 * This file is part of IOWarp Core.
 * See COPYING file in the top-level directory.
 */

#ifndef CHIMAERA_MOD_NAME_GPU_RUNTIME_H_
#define CHIMAERA_MOD_NAME_GPU_RUNTIME_H_

#include "chimaera/gpu_container.h"
#include "chimaera/MOD_NAME/MOD_NAME_tasks.h"
#include "chimaera/MOD_NAME/autogen/MOD_NAME_methods.h"

namespace chimaera::MOD_NAME {

/**
 * GPU-side container for the MOD_NAME module.
 * Processes GpuSubmitTask on the GPU work orchestrator.
 */
class GpuRuntime : public chi::gpu::Container {
 public:
  HSHM_GPU_FUN GpuRuntime() = default;
  HSHM_GPU_FUN ~GpuRuntime() override = default;

  /**
   * GPU handler for GpuSubmit method.
   * @param task The GPU submit task containing test_value_ and gpu_id_ inputs
   *             and result_value_ output.
   * @param rctx GPU run context.
   */
  HSHM_GPU_FUN void GpuSubmit(hipc::FullPtr<GpuSubmitTask> task,
                                chi::gpu::GpuRunContext &rctx);

  // Autogenerated virtual method overrides (switch-case dispatch)
  #include "autogen/MOD_NAME_gpu_lib_exec.h"
};

}  // namespace chimaera::MOD_NAME

#endif  // CHIMAERA_MOD_NAME_GPU_RUNTIME_H_
