/*
 * Copyright (c) 2024, Gnosis Research Center, Illinois Institute of Technology
 * All rights reserved.
 * This file is part of IOWarp Core.
 * See COPYING file in the top-level directory.
 */

#ifndef CHIMAERA_MOD_NAME_GPU_RUNTIME_H_
#define CHIMAERA_MOD_NAME_GPU_RUNTIME_H_

#include "chimaera/gpu_container.h"
#include "chimaera/singletons.h"
#include "chimaera/MOD_NAME/MOD_NAME_tasks.h"
#include "chimaera/MOD_NAME/autogen/MOD_NAME_methods.h"

namespace chimaera::MOD_NAME {

/**
 * GPU-side container for the MOD_NAME module.
 * Processes GpuSubmitTask on the GPU work orchestrator.
 */
class GpuRuntime : public chi::gpu::Container {
 public:
  // Constructor is autogenerated (sets function pointer table)
  ~GpuRuntime() = default;

  /**
   * GPU handler for GpuSubmit method.
   * @param task The GPU submit task containing test_value_ and gpu_id_ inputs
   *             and result_value_ output.
   * @param rctx GPU run context.
   */
  /**
   * GPU handler for SubtaskTest method.
   * Dispatches GpuSubmit on self and spin-polls for completion.
   */
  HSHM_GPU_FUN void SubtaskTest(
      hipc::FullPtr<SubtaskTestTask> task,
      chi::gpu::RunContext &rctx);

  HSHM_GPU_FUN void GpuSubmit(hipc::FullPtr<GpuSubmitTask> task,
                                chi::gpu::RunContext &rctx) {
    task->result_value_ = (task->test_value_ * 3) + task->gpu_id_;
#if !HSHM_IS_HOST
    if (task->counter_addr_) {
      atomicAdd(reinterpret_cast<unsigned int*>(task->counter_addr_), 1u);
    }
#endif
  }

  // Autogenerated virtual method overrides (switch-case dispatch)
  #include "autogen/MOD_NAME_gpu_lib_exec.h"
};

}  // namespace chimaera::MOD_NAME

#endif  // CHIMAERA_MOD_NAME_GPU_RUNTIME_H_
