// Auto-generated GPU lib_exec for core
// Include inside GpuRuntime class body.
// Run() dispatches to typed handler methods.
// LocalAllocLoadTask and LocalSaveTask are no-ops (tasks are allocated/freed
// on CPU; GPU only accesses already-allocated task memory via Cast<>).
// This file is autogenerated - do not edit manually.

HSHM_GPU_FUN chi::gpu::TaskResume Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr,
                                      chi::gpu::RunContext &rctx) override {
  switch (method) {
    case Method::kRegisterTarget: {
      auto typed = task_ptr.template Cast<RegisterTargetTask>();
      co_await RegisterTarget(typed, rctx);
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed = task_ptr.template Cast<UnregisterTargetTask>();
      co_await UnregisterTarget(typed, rctx);
      break;
    }
    case Method::kListTargets: {
      auto typed = task_ptr.template Cast<ListTargetsTask>();
      co_await ListTargets(typed, rctx);
      break;
    }
    case Method::kStatTargets: {
      auto typed = task_ptr.template Cast<StatTargetsTask>();
      co_await StatTargets(typed, rctx);
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed = task_ptr.template Cast<GetOrCreateTagTask<CreateParams>>();
      co_await GetOrCreateTag(typed, rctx);
      break;
    }
    case Method::kGetTagSize: {
      auto typed = task_ptr.template Cast<GetTagSizeTask>();
      co_await GetTagSize(typed, rctx);
      break;
    }
    case Method::kDelTag: {
      auto typed = task_ptr.template Cast<DelTagTask>();
      co_await DelTag(typed, rctx);
      break;
    }
    case Method::kGetContainedBlobs: {
      auto typed = task_ptr.template Cast<GetContainedBlobsTask>();
      co_await GetContainedBlobs(typed, rctx);
      break;
    }
    case Method::kPutBlob: {
      auto typed = task_ptr.template Cast<PutBlobTask>();
      co_await PutBlob(typed, rctx);
      break;
    }
    case Method::kGetBlob: {
      auto typed = task_ptr.template Cast<GetBlobTask>();
      co_await GetBlob(typed, rctx);
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed = task_ptr.template Cast<ReorganizeBlobTask>();
      co_await ReorganizeBlob(typed, rctx);
      break;
    }
    case Method::kDelBlob: {
      auto typed = task_ptr.template Cast<DelBlobTask>();
      co_await DelBlob(typed, rctx);
      break;
    }
    case Method::kGetBlobScore: {
      auto typed = task_ptr.template Cast<GetBlobScoreTask>();
      co_await GetBlobScore(typed, rctx);
      break;
    }
    case Method::kGetBlobSize: {
      auto typed = task_ptr.template Cast<GetBlobSizeTask>();
      co_await GetBlobSize(typed, rctx);
      break;
    }
    case Method::kGetBlobInfo: {
      auto typed = task_ptr.template Cast<GetBlobInfoTask>();
      co_await GetBlobInfo(typed, rctx);
      break;
    }
    case Method::kPollTelemetryLog: {
      auto typed = task_ptr.template Cast<PollTelemetryLogTask>();
      co_await PollTelemetryLog(typed, rctx);
      break;
    }
    case Method::kTagQuery: {
      auto typed = task_ptr.template Cast<TagQueryTask>();
      co_await TagQuery(typed, rctx);
      break;
    }
    case Method::kBlobQuery: {
      auto typed = task_ptr.template Cast<BlobQueryTask>();
      co_await BlobQuery(typed, rctx);
      break;
    }
    case Method::kGetTargetInfo: {
      auto typed = task_ptr.template Cast<GetTargetInfoTask>();
      co_await GetTargetInfo(typed, rctx);
      break;
    }
    case Method::kFlushMetadata: {
      auto typed = task_ptr.template Cast<FlushMetadataTask>();
      co_await FlushMetadata(typed, rctx);
      break;
    }
    case Method::kFlushData: {
      auto typed = task_ptr.template Cast<FlushDataTask>();
      co_await FlushData(typed, rctx);
      break;
    }
    default: break;
  }
  co_return;
}

// LocalAllocLoadTask and LocalSaveTask are declared here and defined in
// core_runtime_gpu.cc where core_tasks.h is available for full type definitions.
HSHM_GPU_FUN hipc::FullPtr<chi::Task> LocalAllocLoadTask(
    chi::u32 method, chi::DefaultLoadArchive &archive) override;

HSHM_GPU_FUN void LocalSaveTask(
    chi::u32 method, chi::DefaultSaveArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override;

HSHM_GPU_FUN void LocalLoadTaskOutput(
    chi::u32 method, chi::DefaultLoadArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override;

HSHM_GPU_FUN void LocalDestroyTask(
    chi::u32 method, hipc::FullPtr<chi::Task> &task) override;
