// Auto-generated GPU lib_exec for core
// Include inside GpuRuntime class body.
// Run() dispatches to typed handler methods.
// LocalAllocLoadTask and LocalSaveTask are no-ops (tasks are allocated/freed
// on CPU; GPU only accesses already-allocated task memory via Cast<>).
// This file is autogenerated - do not edit manually.

HSHM_GPU_FUN void Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr,
                       chi::gpu::GpuRunContext &rctx) override {
  switch (method) {
    case Method::kRegisterTarget: {
      auto typed = task_ptr.template Cast<RegisterTargetTask>();
      RegisterTarget(typed, rctx);
      break;
    }
    case Method::kUnregisterTarget: {
      auto typed = task_ptr.template Cast<UnregisterTargetTask>();
      UnregisterTarget(typed, rctx);
      break;
    }
    case Method::kListTargets: {
      auto typed = task_ptr.template Cast<ListTargetsTask>();
      ListTargets(typed, rctx);
      break;
    }
    case Method::kStatTargets: {
      auto typed = task_ptr.template Cast<StatTargetsTask>();
      StatTargets(typed, rctx);
      break;
    }
    case Method::kGetOrCreateTag: {
      auto typed = task_ptr.template Cast<GetOrCreateTagTask<CreateParams>>();
      GetOrCreateTag(typed, rctx);
      break;
    }
    case Method::kGetTagSize: {
      auto typed = task_ptr.template Cast<GetTagSizeTask>();
      GetTagSize(typed, rctx);
      break;
    }
    case Method::kDelTag: {
      auto typed = task_ptr.template Cast<DelTagTask>();
      DelTag(typed, rctx);
      break;
    }
    case Method::kGetContainedBlobs: {
      auto typed = task_ptr.template Cast<GetContainedBlobsTask>();
      GetContainedBlobs(typed, rctx);
      break;
    }
    case Method::kPutBlob: {
      auto typed = task_ptr.template Cast<PutBlobTask>();
      PutBlob(typed, rctx);
      break;
    }
    case Method::kGetBlob: {
      auto typed = task_ptr.template Cast<GetBlobTask>();
      GetBlob(typed, rctx);
      break;
    }
    case Method::kReorganizeBlob: {
      auto typed = task_ptr.template Cast<ReorganizeBlobTask>();
      ReorganizeBlob(typed, rctx);
      break;
    }
    case Method::kDelBlob: {
      auto typed = task_ptr.template Cast<DelBlobTask>();
      DelBlob(typed, rctx);
      break;
    }
    case Method::kGetBlobScore: {
      auto typed = task_ptr.template Cast<GetBlobScoreTask>();
      GetBlobScore(typed, rctx);
      break;
    }
    case Method::kGetBlobSize: {
      auto typed = task_ptr.template Cast<GetBlobSizeTask>();
      GetBlobSize(typed, rctx);
      break;
    }
    case Method::kGetBlobInfo: {
      auto typed = task_ptr.template Cast<GetBlobInfoTask>();
      GetBlobInfo(typed, rctx);
      break;
    }
    case Method::kPollTelemetryLog: {
      auto typed = task_ptr.template Cast<PollTelemetryLogTask>();
      PollTelemetryLog(typed, rctx);
      break;
    }
    case Method::kTagQuery: {
      auto typed = task_ptr.template Cast<TagQueryTask>();
      TagQuery(typed, rctx);
      break;
    }
    case Method::kBlobQuery: {
      auto typed = task_ptr.template Cast<BlobQueryTask>();
      BlobQuery(typed, rctx);
      break;
    }
    case Method::kGetTargetInfo: {
      auto typed = task_ptr.template Cast<GetTargetInfoTask>();
      GetTargetInfo(typed, rctx);
      break;
    }
    case Method::kFlushMetadata: {
      auto typed = task_ptr.template Cast<FlushMetadataTask>();
      FlushMetadata(typed, rctx);
      break;
    }
    case Method::kFlushData: {
      auto typed = task_ptr.template Cast<FlushDataTask>();
      FlushData(typed, rctx);
      break;
    }
    default: break;
  }
}

HSHM_GPU_FUN hipc::FullPtr<chi::Task> LocalAllocLoadTask(
    chi::u32 method, chi::LocalLoadTaskArchive &archive) override {
  (void)method; (void)archive;
  return hipc::FullPtr<chi::Task>::GetNull();
}

HSHM_GPU_FUN void LocalSaveTask(
    chi::u32 method, chi::LocalSaveTaskArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override {
  (void)method; (void)archive; (void)task;
}
