/**
 * Auto-generated execution implementation for simple_mod ChiMod
 * Implements Container virtual APIs (Run, Del, SaveTask, LoadTask, NewCopy, Aggregate)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "external_test/simple_mod/simple_mod_runtime.h"
#include "external_test/simple_mod/autogen/simple_mod_methods.h"
#include <chimaera/chimaera.h>

namespace external_test::simple_mod {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const chi::PoolId &pool_id, const std::string &pool_name,
                   chi::u32 container_id) {
  // Call base class initialization
  chi::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);
}

void Runtime::Run(chi::u32 method, chi::Future<chi::Task>& task_future, chi::RunContext& rctx) {
  switch (method) {
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::Del(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr) {
  // Use IPC manager to deallocate task from private memory
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    default: {
      // For unknown methods, still try to delete from main segment
      ipc_manager->DelTask(task_ptr.GetTaskPtr());
      break;
    }
  }
}

void Runtime::SaveTask(chi::u32 method, chi::SaveTaskArchive& archive, 
                        chi::Future<chi::Task>& task_future) {
  switch (method) {
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(chi::u32 method, chi::LoadTaskArchive& archive, 
                        chi::Future<chi::Task>& task_future) {
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LocalLoadIn(chi::u32 method, chi::LocalLoadTaskArchive& archive, 
                           chi::Future<chi::Task>& task_future) {
  auto* ipc_manager = CHI_IPC;
  
  switch (method) {
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LocalSaveOut(chi::u32 method, chi::LocalSaveTaskArchive& archive, 
                            chi::Future<chi::Task>& task_future) {
  switch (method) {
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::NewCopy(chi::u32 method, chi::Future<chi::Task>& orig_future,
                       chi::Future<chi::Task>& dup_future, bool deep) {
  auto* ipc_manager = CHI_IPC;
  if (!ipc_manager) {
    return;
  }
  
  switch (method) {
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<chi::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(orig_future.GetTaskPtr());
        dup_future = chi::Future<chi::Task>(ipc_manager->GetMainAlloc(), new_task_ptr);
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
}

void Runtime::Aggregate(chi::u32 method, chi::Future<chi::Task>& origin_future,
                         chi::Future<chi::Task>& replica_future) {
  switch (method) {
    default: {
      // For unknown methods, use base Task Aggregate (which also propagates return codes)
      origin_future->Aggregate(replica_future.GetTaskPtr());
      break;
    }
  }
}

} // namespace external_test::simple_mod
