// Auto-generated GPU lib_exec for MOD_NAME
// Include inside GpuRuntime class body
// This file is autogenerated - do not edit manually.

template <typename ArchiveT>
HSHM_GPU_FUN void LoadTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  switch (method) {
    case Method::kGpuSubmit: {
      auto typed = task.template Cast<GpuSubmitTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    case Method::kSubtaskTest: {
      auto typed = task.template Cast<SubtaskTestTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn)
        typed->SerializeIn(archive);
      else
        typed->SerializeOut(archive);
      break;
    }
    default: break;
  }
}

template <typename ArchiveT>
HSHM_GPU_FUN void SaveTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  switch (method) {
    case Method::kGpuSubmit:
      task.template Cast<GpuSubmitTask>()->SerializeOut(archive);
      break;
    case Method::kSubtaskTest:
      task.template Cast<SubtaskTestTask>()->SerializeOut(archive);
      break;
    default: break;
  }
}

static HSHM_GPU_FUN chi::gpu::TaskResume RunImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> task_ptr, chi::gpu::RunContext &rctx) {
  auto *self = static_cast<GpuRuntime *>(self_);
  switch (method) {
    case Method::kGpuSubmit:
      co_await self->GpuSubmit(task_ptr.template Cast<GpuSubmitTask>(), rctx);
      break;
    case Method::kSubtaskTest:
      co_await self->SubtaskTest(task_ptr.template Cast<SubtaskTestTask>(), rctx);
      break;
    default: break;
  }
  co_return;
}

static HSHM_GPU_FUN chi::gpu::TaskContextBlock AllocTaskImpl(
    chi::gpu::Container *self_, chi::u32 method, size_t stack_size) {
  auto *alloc = CHI_IPC->GetPrivAlloc();
  if (!alloc) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
  size_t rctx_total = sizeof(chi::gpu::RunContext) + stack_size;
  switch (method) {
    case Method::kGpuSubmit: {
      auto fp = alloc->template AllocateObjs<char>(sizeof(GpuSubmitTask) + rctx_total);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      new (fp.ptr_) GpuSubmitTask();
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(fp.ptr_ + sizeof(GpuSubmitTask));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    case Method::kSubtaskTest: {
      auto fp = alloc->template AllocateObjs<char>(sizeof(SubtaskTestTask) + rctx_total);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      new (fp.ptr_) SubtaskTestTask();
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(fp.ptr_ + sizeof(SubtaskTestTask));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    default: return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
  }
}

static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method, chi::DefaultLoadArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto block = self->alloc_task_(self_, method, 0);
  if (block.task_ptr.IsNull()) return block.task_ptr;
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  self->LoadTaskTmpl(method, ar, block.task_ptr);
  return block.task_ptr;
}

static HSHM_GPU_FUN hipc::FullPtr<chi::Task> AllocLoadTaskWrapImpl(
    chi::gpu::Container *self_, chi::u32 method, chi::WrapLoadArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto block = self->alloc_task_(self_, method, 0);
  if (block.task_ptr.IsNull()) return block.task_ptr;
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  self->LoadTaskTmpl(method, ar, block.task_ptr);
  return block.task_ptr;
}

static HSHM_GPU_FUN void LoadTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::DefaultLoadArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void LoadTaskWrapImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::WrapLoadArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void SaveTaskDefaultImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::DefaultSaveArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  static_cast<GpuRuntime *>(self_)->SaveTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void SaveTaskWrapImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::WrapSaveArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  static_cast<GpuRuntime *>(self_)->SaveTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN chi::gpu::TaskContextBlock AllocLoadDeserImpl(
    chi::gpu::Container *self_, chi::u32 method,
    size_t stack_size, chi::WrapLoadArchive &ar) {
  auto *self = static_cast<GpuRuntime *>(self_);
  auto block = AllocTaskImpl(self_, method, stack_size);
  if (!block.task_ptr.IsNull()) {
    ar.SetMsgType(chi::LocalMsgType::kSerializeIn);
    self->LoadTaskTmpl(method, ar, block.task_ptr);
  }
  return block;
}

static HSHM_GPU_FUN void LoadTaskOutputImpl(
    chi::gpu::Container *self_, chi::u32 method,
    chi::DefaultLoadArchive &ar, const hipc::FullPtr<chi::Task> &task) {
  ar.SetMsgType(chi::LocalMsgType::kSerializeOut);
  static_cast<GpuRuntime *>(self_)->LoadTaskTmpl(method, ar, task);
}

static HSHM_GPU_FUN void DestroyTaskImpl(
    chi::gpu::Container *self_, chi::u32 method,
    hipc::FullPtr<chi::Task> &task) {
  if (task.IsNull()) return;
  switch (method) {
    case Method::kGpuSubmit:
      task.template Cast<GpuSubmitTask>().ptr_->~GpuSubmitTask();
      break;
    case Method::kSubtaskTest:
      task.template Cast<SubtaskTestTask>().ptr_->~SubtaskTestTask();
      break;
    default: task.ptr_->~Task(); break;
  }
}

HSHM_GPU_FUN GpuRuntime() {
  run_ = &RunImpl;
  alloc_task_ = &AllocTaskImpl;
  alloc_load_deser_ = &AllocLoadDeserImpl;
  alloc_load_task_default_ = &AllocLoadTaskDefaultImpl;
  alloc_load_task_wrap_ = &AllocLoadTaskWrapImpl;
  load_task_default_ = &LoadTaskDefaultImpl;
  load_task_wrap_ = &LoadTaskWrapImpl;
  save_task_default_ = &SaveTaskDefaultImpl;
  save_task_wrap_ = &SaveTaskWrapImpl;
  load_task_output_ = &LoadTaskOutputImpl;
  destroy_task_ = &DestroyTaskImpl;
}
