// Auto-generated GPU lib_exec for MOD_NAME
// Include inside GpuRuntime class body
// This file is autogenerated - do not edit manually.

HSHM_GPU_FUN chi::gpu::TaskResume Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr,
                       chi::gpu::RunContext &rctx) override {
  switch (method) {
    case Method::kGpuSubmit: {
      auto typed = task_ptr.template Cast<GpuSubmitTask>();
      co_await GpuSubmit(typed, rctx);
      break;
    }
    case Method::kSubtaskTest: {
      auto typed = task_ptr.template Cast<SubtaskTestTask>();
      co_await SubtaskTest(typed, rctx);
      break;
    }
    default: break;
  }
  co_return;
}

HSHM_GPU_FUN hipc::FullPtr<chi::Task> LocalAllocLoadTask(
    chi::u32 method, chi::DefaultLoadArchive &archive) override {
  switch (method) {
    case Method::kGpuSubmit: {
      auto *alloc = CHI_IPC->gpu_alloc_;
      auto task = alloc->template AllocateObjs<GpuSubmitTask>(1);
      if (task.IsNull()) return hipc::FullPtr<chi::Task>::GetNull();
      new (task.ptr_) GpuSubmitTask();
      archive.SetMsgType(chi::LocalMsgType::kSerializeIn);
      task.ptr_->SerializeIn(archive);
      return task.template Cast<chi::Task>();
    }
    case Method::kSubtaskTest: {
      auto *alloc = CHI_IPC->gpu_alloc_;
      auto task = alloc->template AllocateObjs<SubtaskTestTask>(1);
      if (task.IsNull()) return hipc::FullPtr<chi::Task>::GetNull();
      new (task.ptr_) SubtaskTestTask();
      archive.SetMsgType(chi::LocalMsgType::kSerializeIn);
      task.ptr_->SerializeIn(archive);
      return task.template Cast<chi::Task>();
    }
    default: return hipc::FullPtr<chi::Task>::GetNull();
  }
}

HSHM_GPU_FUN hipc::FullPtr<chi::Task> LocalAllocTask(
    chi::u32 method) override {
  switch (method) {
    case Method::kGpuSubmit: {
      auto *alloc = CHI_IPC->gpu_alloc_;
      auto task = alloc->template AllocateObjs<GpuSubmitTask>(1);
      if (task.IsNull()) return hipc::FullPtr<chi::Task>::GetNull();
      new (task.ptr_) GpuSubmitTask();
      return task.template Cast<chi::Task>();
    }
    case Method::kSubtaskTest: {
      auto *alloc = CHI_IPC->gpu_alloc_;
      auto task = alloc->template AllocateObjs<SubtaskTestTask>(1);
      if (task.IsNull()) return hipc::FullPtr<chi::Task>::GetNull();
      new (task.ptr_) SubtaskTestTask();
      return task.template Cast<chi::Task>();
    }
    default: return hipc::FullPtr<chi::Task>::GetNull();
  }
}

HSHM_GPU_FUN void LocalLoadTask(
    chi::u32 method, chi::DefaultLoadArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override {
  archive.SetMsgType(chi::LocalMsgType::kSerializeIn);
  switch (method) {
    case Method::kGpuSubmit: {
      auto typed = task.template Cast<GpuSubmitTask>();
      typed->SerializeIn(archive);
      break;
    }
    case Method::kSubtaskTest: {
      auto typed = task.template Cast<SubtaskTestTask>();
      typed->SerializeIn(archive);
      break;
    }
    default: break;
  }
}

HSHM_GPU_FUN void LocalSaveTask(
    chi::u32 method, chi::DefaultSaveArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override {
  switch (method) {
    case Method::kGpuSubmit: {
      auto typed = task.template Cast<GpuSubmitTask>();
      typed->SerializeOut(archive);
      break;
    }
    case Method::kSubtaskTest: {
      auto typed = task.template Cast<SubtaskTestTask>();
      typed->SerializeOut(archive);
      break;
    }
    default: break;
  }
}
