// Auto-generated GPU lib_exec for MOD_NAME
// Include inside GpuRuntime class body
// This file is autogenerated - do not edit manually.

HSHM_GPU_FUN chi::gpu::TaskResume Run(chi::u32 method, hipc::FullPtr<chi::Task> task_ptr,
                       chi::gpu::RunContext &rctx) override {
  switch (method) {
    case Method::kGpuSubmit: {
      auto typed = task_ptr.template Cast<GpuSubmitTask>();
      co_await GpuSubmit(typed, rctx);
      break;
    }
    case Method::kSubtaskTest: {
      auto typed = task_ptr.template Cast<SubtaskTestTask>();
      co_await SubtaskTest(typed, rctx);
      break;
    }
    default: break;
  }
  co_return;
}

template <typename ArchiveT>
HSHM_GPU_FUN void LoadTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  switch (method) {
    case Method::kGpuSubmit: {
      auto typed = task.template Cast<GpuSubmitTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn) {
        typed->SerializeIn(archive);
      } else {
        typed->SerializeOut(archive);
      }
      break;
    }
    case Method::kSubtaskTest: {
      auto typed = task.template Cast<SubtaskTestTask>();
      if (archive.GetMsgType() == chi::LocalMsgType::kSerializeIn) {
        typed->SerializeIn(archive);
      } else {
        typed->SerializeOut(archive);
      }
      break;
    }
    default: break;
  }
}

template <typename ArchiveT>
HSHM_GPU_FUN void SaveTaskTmpl(
    chi::u32 method, ArchiveT &archive,
    const hipc::FullPtr<chi::Task> &task) {
  switch (method) {
    case Method::kGpuSubmit: {
      auto typed = task.template Cast<GpuSubmitTask>();
      typed->SerializeOut(archive);
      break;
    }
    case Method::kSubtaskTest: {
      auto typed = task.template Cast<SubtaskTestTask>();
      typed->SerializeOut(archive);
      break;
    }
    default: break;
  }
}

HSHM_GPU_FUN hipc::FullPtr<chi::Task> LocalAllocLoadTask(
    chi::u32 method, chi::DefaultLoadArchive &archive) override {
  auto block = LocalAllocTask(method, 0);
  if (block.task_ptr.IsNull()) return block.task_ptr;
  archive.SetMsgType(chi::LocalMsgType::kSerializeIn);
  LoadTaskTmpl(method, archive, block.task_ptr);
  return block.task_ptr;
}

HSHM_GPU_FUN hipc::FullPtr<chi::Task> LocalAllocLoadTask(
    chi::u32 method, chi::WrapLoadArchive &archive) override {
  auto block = LocalAllocTask(method, 0);
  if (block.task_ptr.IsNull()) return block.task_ptr;
  archive.SetMsgType(chi::LocalMsgType::kSerializeIn);
  LoadTaskTmpl(method, archive, block.task_ptr);
  return block.task_ptr;
}

HSHM_GPU_FUN TaskContextBlock LocalAllocTask(
    chi::u32 method, size_t stack_size) override {
  auto *alloc = CHI_IPC->GetPrivAlloc();
  if (!alloc) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
  size_t rctx_total = sizeof(chi::gpu::RunContext) + stack_size;
  switch (method) {
    case Method::kGpuSubmit: {
      auto fp = alloc->template AllocateObjs<char>(sizeof(GpuSubmitTask) + rctx_total);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      new (fp.ptr_) GpuSubmitTask();
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(fp.ptr_ + sizeof(GpuSubmitTask));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    case Method::kSubtaskTest: {
      auto fp = alloc->template AllocateObjs<char>(sizeof(SubtaskTestTask) + rctx_total);
      if (fp.IsNull()) return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
      new (fp.ptr_) SubtaskTestTask();
      auto *rctx = reinterpret_cast<chi::gpu::RunContext *>(fp.ptr_ + sizeof(SubtaskTestTask));
      new (rctx) chi::gpu::RunContext();
      rctx->InitStack(reinterpret_cast<char *>(rctx) + sizeof(chi::gpu::RunContext), stack_size);
      return {fp.template Cast<chi::Task>(), rctx};
    }
    default: return {hipc::FullPtr<chi::Task>::GetNull(), nullptr};
  }
}

HSHM_GPU_FUN void LocalLoadTask(
    chi::u32 method, chi::DefaultLoadArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override {
  archive.SetMsgType(chi::LocalMsgType::kSerializeIn);
  LoadTaskTmpl(method, archive, task);
}

HSHM_GPU_FUN void LocalLoadTask(
    chi::u32 method, chi::WrapLoadArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override {
  LoadTaskTmpl(method, archive, task);
}

HSHM_GPU_FUN void LocalSaveTask(
    chi::u32 method, chi::DefaultSaveArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override {
  SaveTaskTmpl(method, archive, task);
}

HSHM_GPU_FUN void LocalSaveTask(
    chi::u32 method, chi::WrapSaveArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override {
  SaveTaskTmpl(method, archive, task);
}

HSHM_GPU_FUN void LocalLoadTaskOutput(
    chi::u32 method, chi::DefaultLoadArchive &archive,
    const hipc::FullPtr<chi::Task> &task) override {
  archive.SetMsgType(chi::LocalMsgType::kSerializeOut);
  LoadTaskTmpl(method, archive, task);
}

HSHM_GPU_FUN void LocalDestroyTask(
    chi::u32 method, hipc::FullPtr<chi::Task> &task) override {
  if (task.IsNull()) return;
  switch (method) {
    case Method::kGpuSubmit:
      task.template Cast<GpuSubmitTask>().ptr_->~GpuSubmitTask();
      break;
    case Method::kSubtaskTest:
      task.template Cast<SubtaskTestTask>().ptr_->~SubtaskTestTask();
      break;
    default:
      task.ptr_->~Task();
      break;
  }
}
